# Generated by Django 5.2.4 on 2026-01-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_calorie_post_carbohydrate_post_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='calorie',
            field=models.FloatField(default=0, verbose_name='칼로리(kcal)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='carbohydrate',
            field=models.FloatField(default=0, verbose_name='탄수화물(g)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fat',
            field=models.FloatField(default=0, verbose_name='지방(g)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='protein',
            field=models.FloatField(default=0, verbose_name='단백질(g)'),
        ),
    ]
