# Generated by Django 5.2.9 on 2026-01-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_starred',
            field=models.BooleanField(default=False, verbose_name='찜 여부'),
        ),
        migrations.DeleteModel(
            name='IdeaStar',
        ),
    ]
