# Generated by Django 5.2.9 on 2026-01-01 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_idea_is_starred_delete_ideastar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='is_starred',
        ),
        migrations.CreateModel(
            name='IdeaStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='server.idea')),
            ],
        ),
    ]
