# Generated by Django 5.2.9 on 2025-12-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('action', '액션'), ('romance', '로맨스'), ('comedy', '코미디'), ('thriller', '스릴러'), ('fantasy', '판타지'), ('drama', '드라마')], max_length=30),
        ),
    ]
