# Generated by Django 5.2.10 on 2026-01-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
