# Generated by Django 5.2.10 on 2026-01-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_tmdb',
            field=models.BooleanField(default=False),
        ),
    ]
